### ISSUE TITLE
Possible `width` bug

### ISSUE THREAD

**Issue by james77777778** [ucsd-hdsi-dvs/V2CE-Toolbox#1]
Initially, thank you for your excellent work.

However, I have encountered an issue that requires me to modify the following line in order for `v2ce.py` to work with arbitrary sizes of video:
https://github.com/ucsd-hdsi-dvs/V2CE-Toolbox/blob/f54da43f9643adbdc2a522a1c7e8cb5ee18be9d2/v2ce.py#L204

The variable `resized_width` needs to be changed to `width`.

Do you think this is a solid solution, or have I overlooked something?
Thank you!

**Comment by lixinghe1999** [comment]
I face a slightly different case, where my input video is 448 * 448, which means width=height, the code can get an error, and I have to change the function (image_pre_processing)
```
#images = np.stack([cv2.resize(img, (int(img.shape[1]/img.shape[0]*height), height)) for img in images], axis=0)
images = np.stack([cv2.resize(img, (width, height)) for img in images], axis=0)
```

**Comment by miracleyoo** [comment]
Thanks for your feedback! I'll check the code and fix it asap.

**Comment by miracleyoo** [comment]
Bug fixed. Close this thread. Thanks again for your support!
